
package main;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Yazilim Laboratuvari I Proje 2
 * @author Oguz Aktas
 */
public class MainWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        this.setTitle("Pseudoinverse Matrix Finder");
    }
    
    public boolean checkInputs() {
        if (text_row.getText().trim().isEmpty() || text_column.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "<html><b>Bir ya da daha fazla alani bos biraktiniz.</b></html>");
            return false;
        } else if (Integer.parseInt(text_row.getText()) > 5 || Integer.parseInt(text_column.getText()) > 5 || Integer.parseInt(text_row.getText()) < 1 || Integer.parseInt(text_column.getText()) < 1) {
            JOptionPane.showMessageDialog(null, "<html><b>Matrisin satir ve sutun boyutlari 5'ten buyuk ve 1'den kucuk olamaz.</b></html>");
            return false;
        } else if (Integer.parseInt(text_row.getText()) == Integer.parseInt(text_column.getText())) {
            JOptionPane.showMessageDialog(null, "<html><b>Matrisin satir ve sutun degerleri esit (kare matris) olamaz.</b></html>");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_baslik = new javax.swing.JLabel();
        label_input = new javax.swing.JLabel();
        Btn_Matrix = new javax.swing.JButton();
        text_column = new javax.swing.JTextField();
        Btn_Create = new javax.swing.JButton();
        text_row = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        label_baslik.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label_baslik.setForeground(new java.awt.Color(44, 29, 111));
        label_baslik.setText("Pseudoinverse Matrix Finder");

        label_input.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_input.setText("Olusturulacak matrisin boyutlarini giriniz [1-5] : ");

        Btn_Matrix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Matrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/matrix.png"))); // NOI18N
        Btn_Matrix.setText(" Rastgele Matris Olustur");
        Btn_Matrix.setIconTextGap(5);
        Btn_Matrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MatrixActionPerformed(evt);
            }
        });

        text_column.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        text_column.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_column.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_columnKeyPressed(evt);
            }
        });

        Btn_Create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/creatematrix.png"))); // NOI18N
        Btn_Create.setText(" Matris Elemanlarini Belirle");
        Btn_Create.setIconTextGap(5);
        Btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateActionPerformed(evt);
            }
        });

        text_row.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        text_row.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_rowKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(label_baslik)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Btn_Matrix, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(label_input)
                        .addGap(9, 9, 9)
                        .addComponent(text_row, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_column, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(label_baslik)
                .addGap(49, 49, 49)
                .addComponent(Btn_Matrix, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_input)
                    .addComponent(text_row, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_column, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MatrixActionPerformed
        this.dispose();
        new RandomMatrixWindow().setVisible(true);
    }//GEN-LAST:event_Btn_MatrixActionPerformed

    private void Btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateActionPerformed
        if (checkInputs()) {
            this.dispose();
            new CreateMatrixWindow(Integer.parseInt(text_row.getText()), Integer.parseInt(text_column.getText())).setVisible(true);
        }
    }//GEN-LAST:event_Btn_CreateActionPerformed

    private void text_rowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_rowKeyPressed
        text_row.setEditable(true);
        int key = evt.getKeyCode();
        if ((key >= evt.VK_1 && key <= evt.VK_5) || (key >= evt.VK_NUMPAD1 && key <= evt.VK_NUMPAD5) || key == KeyEvent.VK_BACKSPACE || (key == KeyEvent.VK_ALT || key == KeyEvent.VK_TAB || key == KeyEvent.VK_ENTER || key == KeyEvent.VK_LEFT || key == KeyEvent.VK_RIGHT)) {
            text_row.setEditable(true);
            text_row.setBackground(Color.YELLOW);
        } else if ((key == evt.VK_0 || key == evt.VK_NUMPAD0)|| (key >= evt.VK_6 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD6 && key <= evt.VK_NUMPAD9)) {
            text_row.setEditable(true);
            text_row.setBackground(Color.RED);
        } else {
            text_row.setEditable(false);
            text_row.setBackground(Color.RED);
        }
    }//GEN-LAST:event_text_rowKeyPressed

    private void text_columnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_columnKeyPressed
        text_column.setEditable(true);
        int key = evt.getKeyCode();
        if ((key >= evt.VK_1 && key <= evt.VK_5) || (key >= evt.VK_NUMPAD1 && key <= evt.VK_NUMPAD5) || key == KeyEvent.VK_BACKSPACE || (key == KeyEvent.VK_ALT || key == KeyEvent.VK_TAB || key == KeyEvent.VK_LEFT || key == KeyEvent.VK_RIGHT)) {
            text_column.setEditable(true);
            text_column.setBackground(Color.YELLOW);
        } else if ((key == evt.VK_0 || key == evt.VK_NUMPAD0)|| (key >= evt.VK_6 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD6 && key <= evt.VK_NUMPAD9)) {
            text_column.setEditable(true);
            text_column.setBackground(Color.RED);
        } else if (key == KeyEvent.VK_ENTER) {
            if (checkInputs()) {
                this.dispose();
                new CreateMatrixWindow(Integer.parseInt(text_row.getText()), Integer.parseInt(text_column.getText())).setVisible(true);
            }
        } else {
            text_column.setEditable(false);
            text_column.setBackground(Color.RED);
        }
    }//GEN-LAST:event_text_columnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Create;
    private javax.swing.JButton Btn_Matrix;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_baslik;
    private javax.swing.JLabel label_input;
    private javax.swing.JTextField text_column;
    private javax.swing.JTextField text_row;
    // End of variables declaration//GEN-END:variables
}
